; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
board_upload.flash_size = 2MB
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
; platform_packages =
;     framework-espidf = D:\Fall_detection\Fall_Detection\esp-idf-v4.4.4
monitor_rts = 0
monitor_dtr = 0
; Thêm timeout để monitor không tự đóng
monitor_filters = 
build_flags = 
    -Os
    -D CONFIG_LOG_DEFAULT_LEVEL=1
    -DCONFIG_MPU_ENABLED=1
    -DCONFIG_MPU_ENABLED

lib_deps = 
    cjson